/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Darlon Franklin
 */
public class FrmMenu extends javax.swing.JFrame {

    private Component frmCadastroCliente;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastroClientes = new javax.swing.JButton();
        btCadastroFornecedores = new javax.swing.JButton();
        btCadastroFuncionarios = new javax.swing.JButton();
        btCadastroVenda = new javax.swing.JButton();
        btCadastroProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        btCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente - resized.png"))); // NOI18N
        btCadastroClientes.setText("Cadastro de Clientes");
        btCadastroClientes.setToolTipText("");
        btCadastroClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCadastroClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroClientesActionPerformed(evt);
            }
        });

        btCadastroFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fornecedor - resized.png"))); // NOI18N
        btCadastroFornecedores.setText("Cadastro de Fornecedores");
        btCadastroFornecedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroFornecedoresActionPerformed(evt);
            }
        });

        btCadastroFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/funcionario - resized.png"))); // NOI18N
        btCadastroFuncionarios.setText("Cadastro de Funcionarios");
        btCadastroFuncionarios.setHideActionText(true);
        btCadastroFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroFuncionariosActionPerformed(evt);
            }
        });

        btCadastroVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vendas - resized.png"))); // NOI18N
        btCadastroVenda.setText("Cadastro de Venda");
        btCadastroVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroVendaActionPerformed(evt);
            }
        });

        btCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/produto - resized.png"))); // NOI18N
        btCadastroProduto.setText("Cadastro de Produto");
        btCadastroProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCadastroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCadastroFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(btCadastroFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCadastroVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastroFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroClientesActionPerformed
    try {
            FrmCadastroClientes frmCadastroClientes = new FrmCadastroClientes();
            frmCadastroClientes.setLocationRelativeTo(null);
            frmCadastroClientes.setResizable(true);
            frmCadastroClientes.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar tela Cadastro de Clientes!", "Erro", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btCadastroClientesActionPerformed

    private void btCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroFornecedoresActionPerformed
    try {
            FrmCadastroFornecedores frmCadastroFornecedores = new FrmCadastroFornecedores();
            frmCadastroFornecedores.setLocationRelativeTo(null);
            frmCadastroFornecedores.setResizable(true);
            frmCadastroFornecedores.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar tela Cadastro de Fornecedores!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCadastroFornecedoresActionPerformed

    private void btCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroFuncionariosActionPerformed
        try {
            FrmCadastroFuncionarios frmCadastroFuncionarios = new FrmCadastroFuncionarios();
            frmCadastroFuncionarios.setLocationRelativeTo(null);
            frmCadastroFuncionarios.setResizable(true);
            frmCadastroFuncionarios.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar tela Cadastro de Funcionarios!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCadastroFuncionariosActionPerformed

    private void btCadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroVendaActionPerformed
        try {
            FrmCadastroVendas frmCadastroVendas = new FrmCadastroVendas();
            frmCadastroVendas.setLocationRelativeTo(null);
            frmCadastroVendas.setResizable(true);
            frmCadastroVendas.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar tela Cadastro de Vendas!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCadastroVendaActionPerformed

    private void btCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroProdutoActionPerformed
        try {
            FrmCadastroProdutos frmCadastroProdutos = new FrmCadastroProdutos();
            frmCadastroProdutos.setLocationRelativeTo(null);
            frmCadastroProdutos.setResizable(true);
            frmCadastroProdutos.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar tela Cadastro de Produtos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCadastroProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastroClientes;
    private javax.swing.JButton btCadastroFornecedores;
    private javax.swing.JButton btCadastroFuncionarios;
    private javax.swing.JButton btCadastroProduto;
    private javax.swing.JButton btCadastroVenda;
    // End of variables declaration//GEN-END:variables
}
